---
title: "Assignment Report - A8(A7)"
author: "Shabbir"
date: "October 31, 2017"
output:
  html_document: default
  pdf_document:
    fig_crop: no
    fig_width: 5
    latex_engine: xelatex
---

```{r setup, echo=F, results='hide',message=F, warning=F, cache=F}
library("ggplot2")
library("tidyr")
library("knitr")
library("kableExtra")
library("scales")
library("plyr")
library("microbenchmark")
library("reshape2")
library("readr")

library("tm")
library("SnowballC")
library("wordcloud")
library("RColorBrewer")
library("grid")
library("gridBase")
library("gridExtra")
library("dplyr")
```

```{r cache=TRUE,echo=F, results = 'asis', warning=F, message=F}
#data <- read.csv('results/stats/timings.csv', sep="\t", header = FALSE)
#data <- data[, c("V1", "V3")]

```

```{r message=False, warning=False, cache=TRUE, include=FALSE, results='asis'}
myReadCSV <- function(fileName){
  read.csv(fileName, sep="\t", header = FALSE)
}
data <- paste(list.files(path=paste(getwd(), "/results/stats", sep=""), full.names=T, recursive=FALSE), "/part-00000", sep="") %>% 
  lapply(myReadCSV) %>% 
  bind_rows   

data <- data[, c("V1", "V3", "V4")]
```

```{r cache=TRUE,echo=F, results = 'asis', warning=F, message=F}
dfRun <- subset(data, substring(data$V1, 0, 3) == "run" & data$V3=="real")
dfRun$V1 <- substring(dfRun$V1, 5)
dfRun %>%
  group_by(V1) %>% 
  summarise(Mean=mean(V4), Median=median(V4)) %>%
  separate("V1", into = paste("V", 1:3, sep = "_")) -> dfRun

colnames(dfRun) <- c("Type", "Tot", "Used", "TimeMean", "TimeMedian")
dfRun$Tot <- as.integer(dfRun$Tot)
dfRun$Used <- as.integer(dfRun$Used)
dfRun <- subset(dfRun, Tot!=0)

dfReg <- subset(dfRun, Type=="reg")
dfPlu <- subset(dfRun, Type=="plugin")
```
```{r cache=TRUE,echo=F, results = 'asis', warning=F, message=F}
dMin <- min(dfRun$TimeMedian)
dMax <- max(dfRun$TimeMedian)
gen_plot <- function(df, title){
  ggplot(data=df, aes(x=reorder(as.factor(Tot), Tot), y=reorder(as.factor(Used), Used), fill=TimeMedian)) +
      geom_tile(width=1, height=1) + 
      scale_fill_gradient(low="white", high="red", name="Time (sec)", limits=c(dMin, dMax)) +
      labs(x="Total # Columns", y="Used # Columns", title=title) + 
      theme_bw()
}
pltR <- gen_plot(dfReg, "Regular")
pltP <- gen_plot(dfPlu, "Plugin")

grid.arrange(pltR, pltP, ncol=2, widths=c(1,1))
```

    
```{r cache=TRUE,echo=F, results = 'asis', warning=F, message=F}
dfAll <- merge(x = dfReg, y = dfPlu, by = c("Tot", "Used"), all = FALSE)

ggplot(data=dfAll, aes(x=reorder(as.factor(Tot), Tot), y=reorder(as.factor(Used), Used), fill=(TimeMedian.y - TimeMedian.x)*100/TimeMedian.x)) +
    geom_tile(width=1, height=1) + 
    scale_fill_gradient2(low="green", mid="ivory", high="red", midpoint=0, name="Time %") +
    labs(x="Total # Columns", y="Used # Columns", title="title") + 
    theme_bw()
```




```{r cache=TRUE,echo=F, results = 'asis', warning=F, message=F}
```








#### Assumptions and Specifications


## Conclusion

